### ISSUE TITLE
Most packets are "Unknown"

### ISSUE THREAD

**Issue by CodeCorrupt** [SapphireServer/ffxivmon#40]
Hello!

I love the idea for the tool! It seems that it's fallen behind with updates and now most of the network traffic is not parsed and left as "unknown" packets. 

I could just be using the tool wrong so please correct me if I'm missing something, All I did was import the code to Visual Studio, update the `GamePath` and run.

**Comment by takhlaq** [comment]
patch 5.3 just hit so it's possible the opcodes aren't updated yet

try changing branch to develop from within the ffxvivmonreborn application and redownload definitions

**Comment by p-doyle** [comment]
It appears to point to develop by default as far as I can tell.  Those definitions do not seem to be correct though despite being updated 25 days ago.  https://github.com/SapphireServer/Sapphire/blob/develop/src/common/Network/PacketDef/Ipcs.h  For example it has the opcode for retainerInformation wrong, it should be 0x014b.  There seems to have been many changes needed after 5.31 that didn't make it in.  The opcodes used by the MachinaJSONWrapper seem to have the correct values: https://github.com/karashiiro/MachinaWrapperJSON/blob/master/MachinaWrapper/Models/Sapphire/Ipcs.cs
Unfortunately the file formats are different so its not a direct replacement...

**Comment by takhlaq** [comment]
this can be closed
